SET SERVEROUTPUT    ON
SET TIMING          ON
SET SQLBLANKLINES   ON
SET DEFINE          OFF
--
ALTER SESSION SET NLS_NUMERIC_CHARACTERS    = '. '
ALTER SESSION SET NLS_DATE_FORMAT           = 'YYYY-MM-DD HH24:MI';
